#!/bin/bash

if [ $# -eq 1 ]; then
    if [[ $1 =~ ^[0-9]+$ ]]; then
        module load Mambaforge/23.3.1-1-hpc1
        ~/.conda/envs/py09_cartopy/bin/jupyter notebook --no-browser --ip=n$1
    else
        echo "Argument is not a number."
    fi
else
    echo "Please provide exactly one argument."
fi
